controller_list:
  - name: fake_arm_controller_controller
    type: $(arg fake_execution_type)
    joints:
      - stationary_base_spin_base_joint
      - spin_base_arm1_joint
      - arm1_arm2_joint
      - arm2_arm3_joint
  - name: fake_gripper_controller_controller
    type: $(arg fake_execution_type)
    joints:
      - arm3_gripper1_joint
      - arm3_gripper2_joint
initial:  # Define initial robot poses per group
  - group: arm_controller
    pose: home
  - group: gripper_controller
    pose: home